
String insert = "INSERT INTO **CLASS_INSTANCE_NAME** (
**FOREACH_FIELD**
**DB_COLUMN_NAME**,
**END_FOREACH_FIELD**
)

VALUES (
**FOREACH_FIELD**
:**DB_COLUMN_NAME**,
**END_FOREACH_FIELD**
)";

